name: Slack Alert for Failed Approve Command Workflow

on:
  workflow_run:
    workflows:
      - 'approve_command.yml'
    types:
      - completed
 

jobs:
  slack_alert:
    name: Slack Alert
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          channel_name: va-mobile-build-alert
          message: 'The `approve_command.yml` workflow has failed.\nRelease Number: ${{ env.RELEASE_NUMBER }}\nWorkflow Run ID: ${{ github.event.workflow_run.id }}\nRepository: ${{ github.repository }}\nCommit: ${{ github.sha }}\nWorkflow URL: ${{ github.event.workflow_run.workflow_url }}'
        run: |
          curl -X POST \
               -H "Authorization: Bearer $SLACK_API_TOKEN" \
               -H "Content-Type: application/json" \
               -d "{\"channel\":\"$channel_name\",\"text\":\"$message\"}" \
               https://slack.com/api/chat.postMessage

