name: Auto-Assign Accessibility Tickets

on:
  issues:
    types:
      - labeled

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v3

      - name: Assign Health team QA
        if: github.event.label.name == 'accessibility'
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-assignee "brea11y"