name: Auto-Assign Accessibility Tickets

on:
  issues:
    types:
      - labeled
  push:
    branches:
          - chanel-9375-test-auto-assign-accessibility


jobs:
  auto-assign:
    if: github.event.label.name == 'accessibility'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Assign ticket to axe specialist
      run: |
        gh issue edit ${{ github.event.issue.number }} --add-assignee "IsraelleHub"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}