name: Auto-Assign Accessibility Tickets

on:
  issues:
    types:
      - labeled

jobs:
  auto-assign:
    if: github.event.label.name == 'accessibility'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  
      
    - name: Assign ticket to axe specialist
      run: gh issue edit ${{ github.event.issue.number }} --add-assignee "IsraelleHub"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}