name: '[Documentation] Test Build'

# Adapted from https://docusaurus.io/docs/deployment

on:
  push:
    branches: [chanel-8217-accessibility-checks]
    paths: 
      - VAMobile/src/components/**
      - VAMobile/documentation/**
      - VAMobile/src/utils/hooks.tsx

jobs:
  test-deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'VAMobile/.nvmrc'
          cache: yarn
          cache-dependency-path: VAMobile/yarn.lock
      - name: Test build
        working-directory: VAMobile
        run: |
          yarn install --frozen-lockfile
          cd documentation
          yarn install --frozen-lockfile
          yarn build

      - name: Run documentation site
        working-directory: VAMob/documentation
        run: yarn start    
  
      - name: Wait for server to start
        run: sleep 10
    
      - name: Run axe
        run: |
            npm install -g @axe-core/cli
            axe http://localhost:3000 --exit        