name: '[Documentation] Accessibility Check'

# Adapted from https://docusaurus.io/docs/deployment

on:
  workflow_dispatch:
  push:
    branches:
      - chanel-8217-accessibility-checks
    # paths: 
    #   - VAMobile/src/components/**
    #   - VAMobile/documentation/**
    #   - VAMobile/src/utils/hooks.tsx

jobs:
  test-deploy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Step 1: Clean npm cache
      - name: Clean npm cache
        run: npm cache clean --force

      # Step 2: Install Axe CLI globally
      - name: Install Axe CLI globally
        run: npm install -g @axe-core/cli@latest

      # Step 3: Update npm
      - name: Update npm
        run: npm install -g npm@latest

  
      # Step 4: Setup Node.js environment  
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'VAMobile/.nvmrc'
          cache: yarn
          cache-dependency-path: VAMobile/yarn.lock

      # Step 5: Install dependencies and build     
      - name: Test build
        working-directory: VAMobile
        run: |
          yarn install --frozen-lockfile
          cd documentation
          yarn install --frozen-lockfile
          yarn build

      # Step 6: Start web server
      - name: Start web server
        working-directory: VAMobile/documentation
        run: npm start & npx wait-on http://localhost:3000 &

      # Step 7: Fetch sitemap and check accessibility for each page
      #- name: Check accessibility issues
      #  id: accessibility_check
      #  run: |
          # Fetch sitemap
    #      wget https://department-of-veterans-affairs.github.io/va-mobile-app/sitemap.xml -O sitemap.xml
          # Extract URLs from sitemap and iterate
    #      for url in $(grep -o '<loc>[^<]*' sitemap.xml | sed 's/<loc>//'); do
     #       axe "$url" --exit || echo "Accessibility issues found in $url"
     #       if [ $? -eq 0 ]; then
   #           echo "Accessibility issues found in $url" >> accessibility_issues.txt
       #     fi
    #      done
      #    accessibility_issues=$(grep -c 'Accessibility issues found' accessibility_issues.txt)
      #    echo "Accessibility issues detected: $accessibility_issues"
          
      
      # Step 7: Check accessibility issues and notify Accessibility Team
      - name: Check accessibility issues
        id: accessibility_check
        run: |
          # Fetch sitemap
          wget https://department-of-veterans-affairs.github.io/va-mobile-app/sitemap.xml -O sitemap.xml
          # Flag to check if any issues are found
          found_issues=false
          # Extract URLs from sitemap and iterate
          for url in $(grep -o '<loc>[^<]*' sitemap.xml | sed 's/<loc>//'); do
            if axe "$url" --exit; then
              echo "No accessibility issues found in $url"
            else
              echo "Accessibility issues found in $url"
              echo "$url" >> accessibility_issues.txt
              found_issues=true
            fi
          done
          # Send notification if issues were found
          if [ "$found_issues" = true ]; then
            echo "Accessibility issues were found. See details in the email." >> email_body.txt
            cat accessibility_issues.txt >> email_body.txt
            mail -s "Accessibility Issues Detected" -a "From: charnelle.domguia@adhocteam.us" charnelle.domguia@adhocteam.us < email_body.txt
          else
            echo "No accessibility issues were found."
          fi

   
    

      # Step 8: Notify Accessibility Team
      #- name: Notify Accessibility Team
     #   if:env.accessibility_issues != '0' }}
       # run: echo "Accessibility issues detected. Please prioritize and fix." | mail -s "Accessibility Issues" charnelle.domguia@adhocteam.com
  
        

      
     # - name: Run accessibility check on single URL
     #   run: axe https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Intro --exit 

     # - name: Check accessibility issues
    #    id: accessibility_check
   #     run: axe https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Intro --exit || echo "ACCESSIBILITY_ISSUES=true" >> $GITHUB_ENV

    
     # - name: Start Slack thread
     #   i
     #   uses: ./.github/workflows/start_slack_thread.yml
     #   with:
     #     channel_name: va-mobile-build-alerts
     #     message: 'Accessibility issues were detected during the first run of the accessibility check. Please review and address them. <{{ github.server_url }}/{{ github.repository }}/actions/runs/{{ github.run_id }}|View workflow run>.'

          
   