
name: '[Documentation] Accessibility Check'

# Adapted from https://docusaurus.io/docs/deployment

on:
  workflow_dispatch:
  # Run on Weekdays at 9:00 AM UTC, 4AM ET, 1:00 AM PT
  schedule:
    - cron: '0 9 * * 1,2,3,4,5'
  push:
    branches:
      [patrick-test-actions]
jobs:
  axe-scan:
    name: Accessibility Check
    runs-on: ubuntu-latest
    outputs:
      num_issues: ${{ steps.accessibility_check.outputs.num_issues }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Axe CLI globally
        run: |
          npm install @axe-core/cli -g
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'VAMobile/.nvmrc'
          cache: yarn
          cache-dependency-path: VAMobile/documentation/yarn.lock
      - name: Install ChromeDriver
        run: npm install -g chromedriver
      - name: Test build
        working-directory: VAMobile
        run: |
          yarn install --frozen-lockfile
      - name: Start web server
        working-directory: VAMobile/documentation
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn start &
          npx wait-on http://localhost:3000 &
          sleep 10
      - name: Check accessibility issues
        id: accessibility_check
        run: |
          # Extract URLs from sitemap and iterate
          output=$(axe "localhost:3000/va-mobile-app/docs/Operations/App%20metrics/Dashboard")
          echo $output
          issues= echo $output | grep -oP '\d+(?= Accessibility issues detected)'
          if [[ ! -z "$issues" ]]
          then
          echo "$issues number of issues"
          else
          echo "no issues"
          fi

