
name: '[Documentation] Accessibility Check'

# Adapted from https://docusaurus.io/docs/deployment

on:
  workflow_dispatch:
  # Run on Weekdays at 9:00 AM UTC, 4AM ET, 1:00 AM PT
  schedule:
    - cron: '0 9 * * 1,2,3,4,5'
  push:
    branches:
      [chanel-8524-automation-accessibility-checks-number-issues]  
jobs:
  axe-scan:
    name: Acessibility Check
    runs-on: ubuntu-latest
    outputs:
      total_issues: ${{ steps.accessibility_check.outputs.total_issues }}
    steps:
      - uses: actions/checkout@v3
      - name: Clean npm cache
        run: npm cache clean --force
      - name: Install Axe CLI globally
        run: npm install -g @axe-core/cli@latest
      - name: Update npm
        run: npm install -g npm@latest
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'VAMobile/.nvmrc'
          cache: yarn
          cache-dependency-path: VAMobile/yarn.lock 
      - name: Test build
        working-directory: VAMobile
        run: |
          yarn install --frozen-lockfile
          cd documentation
          yarn install --frozen-lockfile
          yarn build
      - name: Start web server
        working-directory: VAMobile/documentation
        run: npm start & npx wait-on http://localhost:3000 &          
      - name: Check accessibility issues
        id: accessibility_check
        run: |
          # Path to the downloaded sitemap file
          sitemap_path="VAMobile/documentation/build/sitemap.xml"
    
          # Counter for the number of accessibility issues detected
          total_issues=0
    
          # Extract URLs from sitemap and iterate
          for url in $(grep -o '<loc>[^<]*' "$sitemap_path" | sed 's/<loc>//'); do
            echo "Checking accessibility for $url"
            # Prevent script from exiting if axe command fails
            set +e
            axe_output=$(axe "$url" --stdout)
            axe_exit_code=$?
            set -e
            
            echo "$axe_output"
            
            # Check if axe found issues
            if [ $axe_exit_code -ne 0 ]; then
              echo "Accessibility issues found in $url"
              echo "$url" >> accessibility_issues.txt

              # Extract number of issues from axe output
              issues=$(echo "$axe_output" | grep -oP '\d+ Accessibility issues detected' | grep -oP '\d+')
              if [ -n "$issues" ]; then
                total_issues=$((total_issues + issues))
              fi
            else
              echo "No accessibility issues found in $url"
            fi
          done

          echo "Accessibility issues detected: $total_issues"

          # Set output for number of issues
          echo "total_issues=$total_issues" >> $GITHUB_OUTPUT

          # Fail the workflow if accessibility issues are detected
          if [ "$total_issues" -gt 0 ]; then
            echo "Accessibility issues were detected."    
            exit 1
          else
            echo "No accessibility issues were found."
          fi

  start_slack_thread:
    name: Start Slack thread
    if: ${{ failure() }}
    needs: axe-scan
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: va-mobile-build-alerts
      message: 'Accessibility issues detected. Please review and fix. Build started by ${{ github.actor }}: (:git: `${{ github.ref_name }}`). See :thread: or <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results.  Number of accessibility issues detected: ${{ needs.axe-scan.outputs.total_issues }}'