# On demand builds that can be run via GitHub UI at
# https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml

name: '[Build] On Demand Build'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
      notes:
        description: Notes
env:
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
  CHANNEL_ID: 'C07JWHB0U86'    

jobs:
  queue_build:
    name: Queue Build
    uses: ./.github/workflows/queue_builds.yml
    secrets: inherit
  start_slack_thread:
    name: Start Slack thread
    
    needs: queue_build
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: 'va-mobile-sandbox'
      message: 'On demand build started by ${{ github.actor }}: \"${{ inputs.notes }}\"  (:git: `${{ github.ref_name }}`). This process may take a while. See :thread: or <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results.'
  ios:
    name: iOS On Demand Build
    needs: [queue_build, start_slack_thread]
    uses: ./.github/workflows/build_ios.yml
    secrets: inherit
    with:
      lane: on_demand
      ref: ${{ github.ref_name }}
      environment: ${{ inputs.environment }}
      notes: ${{ inputs.notes }}
      slack_thread_ts: ${{ needs.start_slack_thread.outputs.thread_ts }}
  android:
    name: Android On Demand Build
    needs: [queue_build, start_slack_thread]
    uses: ./.github/workflows/build_android.yml
    secrets: inherit
    with:
      lane: on_demand
      ref: ${{ github.ref_name }}
      environment: ${{ inputs.environment }}
      notes: ${{ inputs.notes }}
      slack_thread_ts: ${{ needs.start_slack_thread.outputs.thread_ts }}

  release_coordination:
    name: release coordination
    needs: [start_slack_thread]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Map GitHub usernames to Slack IDs
        id: map_slack_ids
        run: |
          echo "GITHUB_TO_SLACK_MAP=$(cat <<EOF
          {
            \"DJUltraTom\": \"@tom.gammons\",
            \"kellylein\": \"@kelly\",
            \"dumathane\": \"@Jon\",
            \"timwright12\": \"@Tim Wright\",
            \"ala-yna\": \"@alayna\",
            \"ajsarkar28\": \"@Ameet Sarkar\",
            \"rachelhanster\": \"@Rachel Han\",
            \"DonMcCaugheyUSDS\": \"@Don McCaughey \",
            \"IsraelleHub\": \"@charnelle.domguia\",
            \"rtwell\": \"@rtwell\"
          }
          EOF
          )" >> $GITHUB_ENV
      - name: Notify Slack for release coordination
        env:
          CHANNEL_ID: 'C07JWHB0U86'
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          curl -X POST \
               -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
               -H 'Content-type: application/json' \
               -d '{
                  "channel": "$CHANNEL_ID",
                  "text": "*Release ${{ needs.release_ticket.outputs.versionNumber }} Coordination thread:*\n*Release Ticket:* ${{ needs.release_ticket.outputs.ticketNumber }}\n*Release Report:* Github Report Link to be provided\n*Release Date:* ${{ needs.release_ticket.outputs.releaseDate }}\n\n*Approval Timing:*\n- *QA Approval Due:* ${{ needs.release_ticket.outputs.qaDueDate }}\n- *Product Approval Due:* ${{ needs.release_ticket.outputs.prodDueDate }}\n- *VA Approval Due:* ${{ needs.release_ticket.outputs.vaDueDate }}\n- Tickets Tagged Appropriately: ...\n\n*Contacts:*\n- *Release Testing:* ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}\n- *QART Tech Lead:* ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}n- *Engineering:* ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}, ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}\n- *Mobile Product Approvers:* H&B and Global - @${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}} Global - ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}\n- *VA PO for awareness:* ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}CC: ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}, ${{ fromJson(steps.map_slack_ids.outputs.GITHUB_TO_SLACK_MAP).IsraelleHub}}.",
                  "thread_ts": "'"${{ needs.start_slack_thread.outputs.thread_ts }}"'"
                }' \
             https://slack.com/api/chat.postMessage