# On demand builds that can be run via GitHub UI at
# https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml

name: '[Build] On Demand Build'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
      notes:
        description: Notes
        required: true

jobs:
  queue_build:
    name: Queue Build
    uses: ./.github/workflows/queue_builds.yml
    secrets: inherit
  start_slack_thread:
    name: Start Slack thread
    needs: queue_build
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: va-mobile-build-alerts
      message: 'On demand build started by ${{ github.actor }}: \"${{ inputs.notes }}\"  (:git: `${{ github.ref_name }}`). This process may take a while. See :thread: or <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results.'
  ios:
    name: iOS On Demand Build
    needs: [queue_build, start_slack_thread]
    uses: ./.github/workflows/build_ios.yml
    secrets: inherit
    with:
      lane: on_demand
      ref: ${{ github.ref_name }}
      environment: ${{ inputs.environment }}
      notes: ${{ inputs.notes }}
      slack_thread_ts: ${{ needs.start_slack_thread.outputs.thread_ts }}
  android:
    name: Android On Demand Build
    needs: [queue_build, start_slack_thread]
    uses: ./.github/workflows/build_android.yml
    secrets: inherit
    with:
      lane: on_demand
      ref: ${{ github.ref_name }}
      environment: ${{ inputs.environment }}
      notes: ${{ inputs.notes }}
      slack_thread_ts: ${{ needs.start_slack_thread.outputs.thread_ts }}

  release_coordination:
    name: release coordintion
    needs: [start_slack_thread, android]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack for release coordination
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          curl -X POST \
               -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
               -H 'Content-type: application/json' \
               -d '{
                  "channel": "va-mobile-build-alerts",
                  "text": "*Release ${{ needs.release_ticket.outputs.versionNumber }} Coordination thread:*\n*Release Ticket:* ${{ needs.release_ticket.outputs.ticketNumber }}\n*Release Report:* Github Report Link to be provided\n*Release Date:* ${{ needs.release_ticket.outputs.releaseDate }}\n\n*Approval Timing:*\n- *QA Approval Due:* ${{ needs.release_ticket.outputs.qaDueDate }}\n- *Product Approval Due:* ${{ needs.release_ticket.outputs.prodDueDate }}\n- *VA Approval Due:* ${{ needs.release_ticket.outputs.vaDueDate }}\n- Tickets Tagged Appropriately: ...\n\n*Contacts:*\n- *Release Testing:* @charnelle.domguia\n- *QART Tech Lead:* @TK\n- *Engineering:* @J, @charnelle.domguia\n- *Mobile Product Approvers:* H&B and Global - @Al Global - @Am\n- *VA PO for awareness:* @Ra CC: @D, @charnelle.domguia.",
                  "thread_ts": "'"${{ needs.start_slack_thread.outputs.thread_ts }}"'"
                }' \
             https://slack.com/api/chat.postMessage