# On demand builds that can be run via GitHub UI at
# https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/on_demand_build.yml

name: '[Build] On Demand Build'

on:
  push:
    branches:
      - 'fix/**'
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
      notes:
        description: Notes
        required: true

jobs:
  queue_build:
    name: Queue Build
    uses: ./.github/workflows/queue_builds.yml
    secrets: inherit
  ios:
    name: iOS On Demand Build
    needs: [queue_build]
    uses: ./.github/workflows/build_ios.yml
    secrets: inherit
    with:
      lane: on_demand
      ref: ${{ github.ref_name }}
      environment: ${{ inputs.environment }}
      notes: 'IGNORE - TESTING in CI'