# Release builds that are triggered by the v*.*.* tag. Release tags occur when
# someone comments /approve on the associated release ticket

name: '[Build] Optimize Image'

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+'
      - 'chanel-6809-add--mage-optimization-into-ci-for-app-store-submissions'

jobs:

  optimize_images:
    name: Optimize Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install imagemin-cli
        run: npm install -g imagemin-cli
      - name: Optimize iOS images and list optimized files
        run: |
          echo "Optimized iOS images:"
          for file in Mob/ios/fastlane/screenshots/en-US/*; do
            size_before=$(stat -c%s "$file")
            imagemin "$file" --out-dir=$(dirname "$file")
            size_after=$(stat -c%s "$file")
            if [ "$size_after" -lt "$size_before" ]; then
              echo "$file"
            fi
          done

      - name: Optimize Android images (root) and list optimized files
        run: |
          echo "Optimized Android root images:"
          for file in Mob/android/fastlane/metadata/android/en-US/images/*.{png,jpg,jpeg,gif,svg}; do
            size_before=$(stat -c%s "$file")
            imagemin "$file" --out-dir=$(dirname "$file")
            size_after=$(stat -c%s "$file")
            if [ "$size_after" -lt "$size_before" ]; then
              echo "$file"
            fi
          done
      - name: Commit optimized images
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add VAMobile/ios/fastlane/screenshots/en-US
          git add VAMobile/android/fastlane/metadata/android/en-US/images
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Optimize images before release build"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}