# Image optimization before release build. This workflow commit only images that have been optimized

name: '[Build] Optimize Image'

on:
  push:
    branches:
      - chanel-9687-automation-update-optimization-workflow-to-automatically-push-changes-through-pr

jobs:
  optimize_images:
    name: Optimize Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install imagemin-cli
        run: npm install -g imagemin-cli
      - name: Optimize iOS images
        run:  imagemin VAMobile/ios/fastlane/screenshots/* --out-dir=VAMobile/ios/fastlane/screenshots/en-US
      - name: Optimize Android images
        run: |
          cd VAMobile/android/fastlane/metadata/android/en-US/images/
          imagemin * --out-dir=.
          
          cd phoneScreenshots/
          imagemin * --out-dir=.
          
          cd ../sevenInchScreenshots/
          imagemin * --out-dir=.
      - name: Commit optimized images
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git checkout -b optimize-images-$(date +'%Y%m%d%H%M%S')
          git add VAMobile/ios/fastlane/screenshots/en-US
          git add VAMobile/android/fastlane/metadata/android/en-US/images
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Optimize images before release build"
            git push --set-upstream origin HEAD
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Optimize images before release build"
          branch: optimize-images-$(date +'%Y%m%d%H%M%S')
          title: "Optimize images before release build"
          body: |
            This PR optimizes images in preparation for the release build.