# Image optimization before release build. This workflow commit only images that have been optimized

name: '[Build] Optimize Image'

on:
  push:
    branches:
      - chanel-9687-automation-update-optimization-workflow-to-automatically-push-changes-through-pr

jobs:
  optimize_images:
    name: Optimize Images
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: optimize-images-${{ github.run_id }} # Declare environment variable here
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Install imagemin-cli
        run: npm install -g imagemin-cli
      - name: Optimize iOS images
        run:  imagemin VAMobile/ios/fastlane/screenshots/* --out-dir=VAMobile/ios/fastlane/screenshots/en-US
      - name: Optimize Android images
        run: |
          cd VAMobile/android/fastlane/metadata/android/en-US/images/
          imagemin * --out-dir=.
          
          cd phoneScreenshots/
          imagemin * --out-dir=.
          
          cd ../sevenInchScreenshots/
          imagemin * --out-dir=.
      
      - name: Commit optimized images
        run: |
        
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git checkout -b ${{ env.BRANCH_NAME }}
          git add VAMobile/ios/fastlane/screenshots/en-US
          git add VAMobile/android/fastlane/metadata/android/en-US/images
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Optimize images before release build"
            git push --set-upstream origin HEAD
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: ${{ github.ref_name }}
          title: "Optimize images before release build"
          body: |
            This PR optimizes images in preparation for the release build.
      # Check if a PR was created
      - name: Pull Request Details
        run: |
          echo "Pull request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
      - name: Post message to Slack
        id: post_message
        run: |
          ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
            -H 'Content-type: application/json' \
            --data '{"channel":"va-mobile-app-automation-test-channel","text":"Pull request created: ${{ steps.create_pr.outputs.pull-request-url }}. See :thread: or <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results."}' \
            https://slack.com/api/chat.postMessage|
            jq -r '.ts')