name: '[Build] Optimize Image'

on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+'
      - 'chanel-6809-add--mage-optimization-into-ci-for-app-store-submissions'

jobs:

  optimize_images:
    name: Optimize Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install imagemin-cli
        run: npm install -g imagemin-cli
      - name: List images before optimization
        run: |
          echo "iOS images before optimization:"
          ls -lh VAMobile/ios/fastlane/screenshots/en-US
          echo "Android images before optimization:"
          ls -lh VAMobile/android/fastlane/metadata/android/en-US/images/
          ls -lh VAMobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/
          ls -lh VAMobile/android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/
      - name: Optimize iOS images
        run: |
          cd VAMobile/ios/fastlane/screenshots/en-US
          imagemin * --out-dir=.
      - name: Optimized Android images
        run: |
          cd VAMobile/android/fastlane/metadata/android/en-US/images/
          imagemin *.{png,jpg,jpeg,gif,svg} --out-dir=.

          cd phoneScreenshots/
          imagemin *.{png,jpg,jpeg,gif,svg} --out-dir=.
          
          cd ../sevenInchScreenshots/
          imagemin *.{png,jpg,jpeg,gif,svg} --out-dir=.
          
      - name: Optimized iOS images
        run: |
         echo "Optimized iOS only:"
         ls -lh VAMobile/ios/fastlane/screenshots/en-US
      - name: Optimized Android images
        run: |
          echo "Optimized Android images only:"
          cd VAMobile/android/fastlane/metadata/android/en-US/images/
          ls -lh *.{png,jpg,jpeg,gif,svg}

          cd phoneScreenshots/
          ls -lh *.{png,jpg,jpeg,gif,svg}

          cd ../sevenInchScreenshots/
          ls -lh *.{png,jpg,jpeg,gif,svg}
      - name: Commit optimized images
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add VAMobile/ios/fastlane/screenshots/en-US
          git add VAMobile/android/fastlane/metadata/android/en-US/images
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Optimize images before release build"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}