
#
# Checks if QA approvals are necessary, and if so runs the associated action when a new review is added
#

name: QA Approval

on:
  pull_request:
    types: [opened, edited, converted_to_draft, ready_for_review, reopened]
    paths:
      - 'VAMobile/src/**'
      - 'VAMobile/package.json'
      - '!VAMobile/src/**.test.*'

  pull_request_review:
    types: [submitted, dismissed]

  pull_request_target:
    branches:
      - 'develop'
  push: 
    branches: 
      - 'chanel-6261-qa-approval-workflow'   
jobs:
  check_for_qa_approval:
    name: Check for QA Approval
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Pull Request Reviews
        id: fetch_reviews
        run: |
          approvals=$(curl --request GET \
            --url "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews?per_page=100" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Content-Type: application/json"

      - name: Check QA Approval
        run: |
          approvals="${{ steps.fetch_reviews.outputs.approvals }}"
          required_approval_count=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/department-of-veterans-affairs/va-mobile-app/branches/develop/protection" | jq -r '.required_pull_request_reviews.required_approving_review_count')

          qa_team_members=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/orgs/department/teams/flag/members" | jq -r '.[] | .login')

          if [[ $(echo "$approvals" | jq -r 'length') -gt "$required_approval_count" ]]; then
            for user in $qa_team_members; do
              if [[ $(echo "$approvals" | jq -r 'contains(["'"$user"'"])') == true ]]; then
                echo 'This PR has QA approval to merge'
                exit 0
              fi
            done
            echo 'This PR requires QA approval to merge'
            exit 1
          else
            echo 'This PR requires 2 approvals, including one QA and one engineer, before merging.'
            exit 1
          fi

          - name: Debug Output
  
