# Release builds that are triggered by the v*.*.* tag. Release tags occur when
# someone comments /approve on the associated release ticket

name: '[Build] Release Build'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  queue_build:
    name: Queue Build
    uses: ./.github/workflows/queue_builds.yml
    secrets: inherit
  start_slack_thread:
    name: Start Slack thread
    needs: queue_build
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: 'va-mobile-app'
      message: 'Automation starting release build for the app. This build will be sent to the app stores for review upon completion. Please see :thread: for results. This process may take a while.'

  optimize_images:
    name: Optimize Images
    needs: start_slack_thread
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ImageOptim-CLI
        run: brew install imageoptim-cli

      - name: Optimize iOS images
        run: imageoptim -d VAMobile/ios/fastlane/screenshots

      - name: Optimize Android images
        run: imageoptim -d VAMobile/android/fastlane/metadata/android/en-US/images

      - name: Commit optimized images
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add ./path/to/images
          git commit -m "Optimize images before release build"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
  ios:
    name: iOS Release Build
    needs: [start_slack_thread, optimize_images]
    uses: ./.github/workflows/build_ios.yml
    secrets: inherit
    with:
      environment: production
      lane: review
      slack_thread_ts: ${{needs.start_slack_thread.outputs.thread_ts}}
      version: ${{ github.ref_name }}
  notify_ios_failure:
    name: Notify ios Failure
    needs: [start_slack_thread, ios]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on iOS failure
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          curl -X POST \
               -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
               -H 'Content-type: application/json' \
               -d '{"channel": "va-mobile-app", "text": "The release build failed for iOS version ${{ github.ref_name }}. See <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for details.", "thread_ts": "${{ needs.start_slack_thread.outputs.thread_ts }}"}' \
               https://slack.com/api/chat.postMessage  
  android:
    name: Android Release Build
    needs: [start_slack_thread, optimize_images]
    uses: ./.github/workflows/build_android.yml
    secrets: inherit
    with:
      environment: production
      lane: review
      slack_thread_ts: ${{needs.start_slack_thread.outputs.thread_ts}}
      version: ${{ github.ref_name }}
  notify_android_failure:
    name: Notify Android Failure
    needs: [start_slack_thread, android]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack on Android failure
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          curl -X POST \
               -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
               -H 'Content-type: application/json' \
               -d '{"channel": "va-mobile-app", "text": "The release build failed for Android version ${{ github.ref_name }}. See <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for details.", "thread_ts": "${{ needs.start_slack_thread.outputs.thread_ts }}"}' \
               https://slack.com/api/chat.postMessage