name: '[Build] test'

on:
  push:
    branches:
        - chanel-6812-automate-notification-release-ticket-to-ssigned-people

jobs:
  start_slack_thread:
    name: Start Slack thread
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      channel_name: va-mobile-sandbox
      message: '*Release $version Coordination :thread:'
  release_coordination:
    name: release coordination
    needs: [start_slack_thread]
    runs-on: ubuntu-latest
    steps:
      - name: Map GitHub usernames to Slack IDs
        id: map_slack_ids
        run: |
          
          declare -A GITHUB_TO_SLACK_MAP
          GITHUB_TO_SLACK_MAP["DJUltraTom"]="U02BBL9L0CU"
          GITHUB_TO_SLACK_MAP["kellylein"]="UJHA49K6X"
          GITHUB_TO_SLACK_MAP["dumathane"]="U02RC1BRZBP"
          GITHUB_TO_SLACK_MAP["timwright12"]="U01DBDAJZ18"
          GITHUB_TO_SLACK_MAP["ala_yna"]="UQC180926"
          GITHUB_TO_SLACK_MAP["ajsarkar28"]="U05BNQLJ9UZ"
          GITHUB_TO_SLACK_MAP["rachelhanster"]="U047Q1LKDFY"
          GITHUB_TO_SLACK_MAP["DonMcCaugheyUSDS"]="U06PCD1R0EL"
          GITHUB_TO_SLACK_MAP["IsraelleHub"]="U06N7M2QSUA"
          GITHUB_TO_SLACK_MAP["rtwell"]="UEY4D750B"
          # Example: Convert mapping to environment variables
          for key in "${!GITHUB_TO_SLACK_MAP[@]}"; do
            echo "${key}=${GITHUB_TO_SLACK_MAP[$key]}" >> $GITHUB_ENV
          done
      - name: Notify Slack for release coordination
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_DJUltraTom: $DJUltraTom
          SLACK_kellylein: $kellylein
          SLACK_dumathane: $dumathane
          SLACK_timwright12: $timwright12
          SLACK_alayna: $ala_yna
          SLACK_ajsarkar28: $ajsarkar28
          SLACK_rachelhanster: $rachelhanster
          SLACK_DonMcCaugheyUSDS: $DonMcCaugheyUSDS
          SLACK_IsraelleHub: $IsraelleHub
          SLACK_rtwel: $rtwell
        run: |
          SLACK_MESSAGE=$(cat <<EOF
        
          {
            "channel": "va-mobile-sandbox",
            "text": "*Release '${{ needs.release_ticket.outputs.versionNumber }}' Coordination :thread:*\n*Release Ticket:* ${{ needs.release_ticket.outputs.ticketNumber }}\n*Release Report:* Github Report Link to be provided\n*Release Date:* ${{ needs.release_ticket.outputs.releaseDate }}\n\n*Approval Timing:*\n- *QA Approval Due:* ${{ needs.release_ticket.outputs.qaDueDate }}\n- *Product Approval Due:* ${{ needs.release_ticket.outputs.prodDueDate }}\n- *Release Manager Approval Due:* ${{ needs.release_ticket.outputs.vaDueDate }}\n- *Tickets Tagged Appropriately:* ${{ needs.release_ticket.outputs.qaDueDate }}\n\n*Contacts:*\n- *Release Testing:* <@${SLACK_IsraelleHub}>\n- *Release Manager:* <@${SLACK_IsraelleHub}>\n- *Release Ticket Validation:* <@${SLACK_IsraelleHub}>\n- *Engineering:* <@${SLACK_IsraelleHub}>, <@${SLACK_IsraelleHub}>\n- *Mobile Product Approvers:* H&B and Global - <@${SLACK_IsraelleHub}> Global - <@${SLACK_IsraelleHub}>\n- *VA PO for awareness:* <@${SLACK_IsraelleHub}> CC: <@${SLACK_IsraelleHub}>, <@${SLACK_IsraelleHub}>,"
            "thread_ts":"${{needs.start_slack_thread.outputs.thread_ts}}"
          }
          EOF
          )
          echo "$SLACK_MESSAGE" | envsubst | curl -X POST \
               -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
               -H 'Content-type: application/json' \
               -d @- \
               https://slack.com/api/chat.postMessage