name: '[Build] test'

on:
  push:
    branches:
        - chanel-6812-automate-notification-release-ticket-to-ssigned-people

jobs:
  start_slack_thread:
    name: Start Slack thread
    runs-on: ubuntu-latest
    steps:
      - name: Start Slack thread
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          thread_ts=$(curl -X POST \
            -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
            -H 'Content-type: application/json' \
            -d '{
              "channel": "va-mobile-test",
              "text": "On demand build started by ${{ github.actor }}: \"${{ github.event.inputs.notes }}\"  (:git: `${{ github.ref_name }}`). This process may take a while. See :thread: or <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|workflow run> for results."
            }' \
            https://slack.com/api/chat.postMessage | jq -r '.ts')

          echo "thread_ts=$thread_ts" >> $GITHUB_ENV
  release_coordination:
    name: release coordination
    needs: [start_slack_thread]
    runs-on: ubuntu-latest
    steps:
      - name: Map GitHub usernames to Slack IDs
        id: map_slack_ids
        run: |
          
          echo "SLACK_DJUltraTom=U02BBL9L0CU" >> $GITHUB_ENV
          echo "SLACK_kellylein=UJHA49K6X" >> $GITHUB_ENV
          echo "SLACK_dumathane=U02RC1BRZBP" >> $GITHUB_ENV
          echo "SLACK_timwright12=U01DBDAJZ18" >> $GITHUB_ENV
          echo "SLACK_ala-yna=UQC180926" >> $GITHUB_ENV
          echo "SLACK_ajsarkar28=U05BNQLJ9UZ" >> $GITHUB_ENV
          echo "SLACK_rachelhanster=U047Q1LKDFY" >> $GITHUB_ENV
          echo "SLACK_DonMcCaugheyUSDS=U06PCD1R0EL" >> $GITHUB_ENV
          echo "SLACK_IsraelleHub:=U06N7M2QSUA" >> $GITHUB_ENV
          echo "SLACK_rtwel=UEY4D750B" >> $GITHUB_ENV
      - name: Notify Slack for release coordination
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_DJUltraTom: ${{ env.SLACK_DJUltraTom }}
          SLACK_kellylein: ${{ env.SLACK_kellylein }}
          SLACK_dumathane: ${{ env.SLACK_dumathane}}
          SLACK_timwright12: ${{ env.SLACK_timwright12 }}
          SLACK_ala-yna: ${{ env.SLACK_ala-yna}}
          SLACK_ajsarkar28: ${{ env.SLACK_ajsarkar28 }}
          SLACK_rachelhanster: ${{ env.SLACK_rachelhanster }}
          SLACK_DonMcCaugheyUSDS: ${{ env.SLACK_DonMcCaugheyUSDS }}
          SLACK_IsraelleHub: ${{ env.SLACK_IsraelleHub }}
          SLACK_rtwel: ${{ env.SLACK_rtwel }}
          SLACK_USER_ID: U06N7M2QSUA
        run: |
          curl -X POST \
               -H 'Authorization: Bearer '"$SLACK_API_TOKEN" \
               -H 'Content-type: application/json' \
               -d '{
                  "channel": "va-mobile-test",
                  "text": "*Release ${{ needs.release_ticket.outputs.versionNumber }} Coordination thread:*\n*Release Ticket:* ${{ needs.release_ticket.outputs.ticketNumber }}\n*Release Report:* Github Report Link to be provided\n*Release Date:* ${{ needs.release_ticket.outputs.releaseDate }}\n\n*Approval Timing:*\n- *QA Approval Due:* ${{ needs.release_ticket.outputs.qaDueDate }}\n- *Product Approval Due:* ${{ needs.release_ticket.outputs.prodDueDate }}\n- *VA Approval Due:* ${{ needs.release_ticket.outputs.vaDueDate }}\n- Tickets Tagged Appropriately: ...\n\n*Contacts:*\n- *Release Testing:* <@${{ env.SLACK_IsraelleHub }}>\n- *QART Tech Lead:* <@${{ env.SLACK_IsraelleHub }}>\n- *Engineering:* <@${{ env.SLACK_IsraelleHub }}>, <@${{ env.SLACK_IsraelleHub }}>\n- *Mobile Product Approvers:* H&B and Global - <@${{ env.SLACK_IsraelleHub }}> Global - <@${{ env.SLACK_IsraelleHub }}>\n- *VA PO for awareness:* <@${{ env.SLACK_IsraelleHub }}> CC: <@${{ env.SLACK_IsraelleHub }}>, <@${{ env.SLACK_IsraelleHub }}>, <@U06N7M2QSUA>.",
                  "thread_ts": "${{ needs.start_slack_thread.outputs.thread_ts }}"
                }' \
             https://slack.com/api/chat.postMessage