# test build

name: '[test] testing'

on:
  push:
    branches:
        - chanel-6808-create-system-for-updating-names-on-release-tickets

jobs:

  release_ticket:
    runs-on: ubuntu-latest
    outputs:
      ticketNumber: ${{steps.create-issue.outputs.number}}
      versionNumber: ${{env.VERSION}}
      releaseDate: ${{env.RELEASE_DATE}}
      qaDueDate: ${{env.QA_DUE_DATE}}
      prodDueDate: ${{env.PROD_DUE_DATE}}
      vaDueDate: ${{env.VA_DUE_DATE}}
    steps:
      - run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: echo "QA_DUE_DATE=$(date -d "+2 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "PROD_DUE_DATE=$(date -d "+5 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "VA_DUE_DATE=$(date -d "+6 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "RELEASE_DATE=$(date -d "+13 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.GH_ACTIONS_PAT }}" > token.txt
      - run: gh auth login --with-token < token.txt
      # Fetch GitHub Group Members
      - name: Fetch GitHub Group Members
        run: |
          TEAM_MEMBERS=$(gh api orgs/department-of-veterans-affairs/teams/flagship-mobile-release-approvers/members --jq '.[].login')
          echo "Team Members: $TEAM_MEMBERS"
          ASSIGNEES=$(echo $TEAM_MEMBERS | tr '\n' ',')
          ASSIGNEES=${ASSIGNEES%,}
          echo "ASSIGNEES=$ASSIGNEES" >> $GITHUB_ENV
      - name: Debug - Output Team Members
        run: |
          echo "Team Members: $ASSIGNEES"

      - name: Update Release Ticket Template with Assignees
        run: |
          # Update the assignees line in the template file with the fetched team members
          sed -i "s/^assignees:.*$/assignees: $TEAM_MEMBERS/" .github/ISSUE_TEMPLATE/update_release_issue.md

      - name: Create Release Ticket
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/update_release_issue.md
        env:
          versionNumber: ${{ env.VERSION }}
          qaDueDate: ${{ env.QA_DUE_DATE }}
          prodDueDate: ${{ env.PROD_DUE_DATE }}
          vaDueDate: ${{ env.VA_DUE_DATE }}
          releaseDate: ${{ env.RELEASE_DATE }}
          issues: ${{ env.TABLE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-issue

      - name: Verify Assignees on Ticket
        run: |
          # Output the ticket number and check if the assignees were applied correctly
          TICKET_NUM=${{ steps.create-issue.outputs.number }}
          gh issue view $TICKET_NUM --json assignees --jq '.assignees'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}