
# test build

name: '[test] testing'

on:
  push:
    branches:
        - chanel-6808-create-system-for-updating-names-on-release-tickets

jobs:

  release_ticket:
    runs-on: ubuntu-latest
    outputs:
      ticketNumber: ${{steps.create-issue.outputs.number}}
      versionNumber: ${{env.VERSION}}
      releaseDate: ${{env.RELEASE_DATE}}
      qaDueDate: ${{env.QA_DUE_DATE}}
      prodDueDate: ${{env.PROD_DUE_DATE}}
      vaDueDate: ${{env.VA_DUE_DATE}}
    steps:
      - run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: echo "QA_DUE_DATE=$(date -d "+2 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "PROD_DUE_DATE=$(date -d "+5 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "VA_DUE_DATE=$(date -d "+6 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "RELEASE_DATE=$(date -d "+13 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.GH_ACTIONS_PAT }}" > token.txt
      - run: gh auth login --with-token < token.txt
      - name: Fetch GitHub Group Members
        run: |
          TEAM_MEMBERS=$(gh api orgs/department-of-veterans-affairs/teams/flagship-mobile-release-approvers/members --jq 'map(.login) | join(",")')
          ASSIGNEES=$(echo $TEAM_MEMBERS | paste -sd "," -)
          # Debug output just for testing
          echo "Formatted Assignees: $ASSIGNEES" 
      # Create Release Ticket with auto-assigned members
      - name: Create Release Ticket
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/update_release_issue.md
        env:
          versionNumber: ${{ env.VERSION }}
          qaDueDate: ${{env.QA_DUE_DATE}}
          prodDueDate: ${{env.PROD_DUE_DATE}}
          vaDueDate: ${{env.VA_DUE_DATE}}
          releaseDate: ${{ env.RELEASE_DATE }}
          issues: ${{ env.TABLE }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_issue
      - name: Assign Users to Release Ticket
        if: ${{ success() }}

        run: |
          echo "Formatted Assignees: $ASSIGNEES" 
          ISSUE_NUMBER=${{ steps.create_issue.outputs.number }}
          gh issue edit $ISSUE_NUMBER --add-assignee "$ASSIGNEES"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}