# test build

name: '[test] testing'

on:
  push:
    branches:
        - chanel-6808-create-system-for-updating-names-on-release-tickets

jobs:

  release_ticket:
    runs-on: ubuntu-latest
    outputs:
      ticketNumber: ${{steps.create-issue.outputs.number}}
      versionNumber: ${{env.VERSION}}
      releaseDate: ${{env.RELEASE_DATE}}
      qaDueDate: ${{env.QA_DUE_DATE}}
      prodDueDate: ${{env.PROD_DUE_DATE}}
      vaDueDate: ${{env.VA_DUE_DATE}}
    steps:
      - run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: echo "QA_DUE_DATE=$(date -d "+2 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "PROD_DUE_DATE=$(date -d "+5 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "VA_DUE_DATE=$(date -d "+6 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - run: echo "RELEASE_DATE=$(date -d "+13 days" '+%A %b %d, %Y')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.GH_ACTIONS_PAT }}" > token.txt
      - run: gh auth login --with-token < token.txt
      # Fetch GitHub Group Members
      - name: Fetch GitHub Group Members
        run: |
          TEAM_MEMBERS=$(gh api orgs/department-of-veterans-affairs/teams/flagship-mobile-release-approvers/members --jq 'map(.login) | join(",")')
          ASSIGNEES=$(echo $TEAM_MEMBERS | paste -sd "," -)
          echo "ASSIGNEES=$ASSIGNEES" >> $GITHUB_ENV
          # Update the markdown file to use the new assignees list
          sed -i "s/^assignees:.*$/assignees: [$ASSIGNEES]/" .github/ISSUE_TEMPLATE/update_releaseissue.md
          echo "Updated Markdown File Content:"
          cat .github/ISSUE_TEMPLATE/update_releaseissue.md
      - name: Commit and Push Assignees Update to Markdown
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .github/ISSUE_TEMPLATE/update_releaseissue.md
          git commit -m "Update assignees in release issue template"
          git push      

      - name: Debug - Output Team Members
        run: |
          echo "Formatted Assignees: $ASSIGNEES"